### ISSUE TITLE
GitHub: Failed to install addon error

### ISSUE THREAD

**Issue by LarssonOliver** [jliddev/WowUp#187]
Hi, not sure if this is on your or the addon developer's side so feel free to close if not relevant.

When trying to install [MayronUI](https://github.com/Mayron/MayronUI-Official) through GitHub a "Failed to install addon" error is shown.

The log file shows the following:
```
System.ArgumentException: extension (Parameter 'Parameter "extension" must not be empty or whitespace.')
   at SixLabors.ThrowHelper.ThrowArgumentException(String message, String name)
   at SixLabors.ThrowHelper.ThrowArgumentExceptionForNotNullOrWhitespace(String value, String name)
   at SixLabors.ImageSharp.Formats.ImageFormatManager.FindFormatByFileExtension(String extension)
   at SixLabors.ImageSharp.Advanced.AdvancedImageExtensions.DetectEncoder(Image source, String filePath)
   at SixLabors.ImageSharp.ImageExtensions.Save(Image source, String path)
   at WowUp.WPF.Services.AddonService.CacheThumbnail(Addon addon)
2020-10-20 11:43:32.583 +02:00 [ERR] Failed to install addon
System.NullReferenceException: Object reference not set to an instance of an object.
   at WowUp.WPF.AddonProviders.GitHubAddonProvider.GetValidAsset(GitHubRelease release, WowClientType clientType)
   at WowUp.WPF.AddonProviders.GitHubAddonProvider.Search(Uri addonUri, WowClientType clientType)
   at WowUp.WPF.Services.AddonService.GetAddonByUri(Uri addonUri, WowClientType clientType, Action`2 onUpdate)
   at WowUp.WPF.ViewModels.InstallUrlDialogViewModel.ImportUrl(String input)
```

From what I've tested, this is the only addon that fails.

**Comment by BloodDragon2580** [comment]
MayronUI has Release file that is the problem. It's not WoWUp.

**Comment by LarssonOliver** [comment]
Thanks, closing.
