### ISSUE TITLE
When Addons folder already contains backup from the last (possibly unsuccessful) install attempt the next install fails

### ISSUE THREAD

**Issue by Phoenix-** [jliddev/WowUp#207]
WowUp Version: 1.18.4
Exception from log:
`2020-10-23 18:27:54.381 +03:00 [ERR] InstallAddon
System.IO.IOException: Cannot create 'C:\Games\World of Warcraft\_retail_\Interface\AddOns\ArkInventory-bak' because a file or directory with the same name already exists.
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at WowUp.WPF.Services.AddonService.<>c__DisplayClass49_0.<<InstallUnzippedDirectory>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at WowUp.WPF.Services.AddonService.InstallUnzippedDirectory(String unzippedDirectory, WowClientType clientType)
   at WowUp.WPF.Services.AddonService.InstallAddon(Int32 addonId, Action``2 updateAction)
`
Proposed solution: pre-check the existence of -bak folder and use smth like -bak2/-bak3, etc.

**Comment by jliddev** [comment]
See if this still happens in the 2.0 beta.

**Comment by Phoenix-** [comment]
Will do, thanks.

**Comment by Phoenix-** [comment]
Cannot reproduce, seems fixed
