### ISSUE TITLE
[v1.19.0-beta.5] ELVUI not updating - showing wrong version

### ISSUE THREAD

**Issue by Barracuda666** [jliddev/WowUp#256]
Hi,

my elvui is on 12.06
WOWUP says its 12.05 and needs update. 
Clicking update: Downloads and installs but does not change the elvui Version.
Checking in on the .TOC says 12.06

`2020-10-29 09:28:23.433 +01:00 [ERR] InstallAddon
System.IO.IOException: Cannot create 'C:\spiele\wow\_retail_\Interface\AddOns\ElvUI-bak' because a file or directory with the same name already exists.
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at WowUp.WPF.Services.AddonService.<>c__DisplayClass59_0.<<InstallUnzippedDirectory>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at WowUp.WPF.Services.AddonService.InstallUnzippedDirectory(String unzippedDirectory, WowClientType clientType)
   at WowUp.WPF.Services.AddonService.InstallAddon(Int32 addonId, Action`2 updateAction)
2020-10-29 09:32:06.233 +01:00 [INF] Caching thumbnail ElvUI: https://www.tukui.org/images/screenshots/DarkTheme_ThickBorders_DPS.jpg
2020-10-29 09:32:13.685 +01:00 [INF] Downloading Zip File: https://www.tukui.org/downloads/elvui-12.06.zip
2020-10-29 09:32:19.759 +01:00 [ERR] InstallAddon
System.IO.IOException: Cannot create 'C:\spiele\wow\_retail_\Interface\AddOns\ElvUI-bak' because a file or directory with the same name already exists.
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at WowUp.WPF.Services.AddonService.<>c__DisplayClass59_0.<<InstallUnzippedDirectory>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at WowUp.WPF.Services.AddonService.InstallUnzippedDirectory(String unzippedDirectory, WowClientType clientType)
   at WowUp.WPF.Services.AddonService.InstallAddon(Int32 addonId, Action`2 updateAction)
`

**Comment by Barracuda666** [comment]
SOLVED

HMPF if only I could read :-(
I dont delete this post, maybe its useful.

I deleted the elvui-bak Folder and everything is fine now.
